### PR TITLE
fix dingling pointwer

### PR DESCRIPTION
**Pull request by Pato05**

### CODE REVIEW

**Comment by Pato05** [comment]
introduced by #2 cos @ItsVixano can't code smh

**Comment by ItsVixano** [comment]
I can't write a proper markdown ;-;

**Comment by Pato05** [comment]
yeah shame on youOn 21 Aug 2022 13:13, Giovanni Ricca ***@***.***> wrote:
I can't write a proper markdown ;-;

**Comment by Pato05** [comment]
github moment

**Comment by ItsVixano** [comment]
imagine replying from emails

**Comment by Pato05** [comment]
🤡On 21 Aug 2022 13:22, Giovanni Ricca ***@***.***> wrote:
imagine replying from emails

**Comment by Pato05** [comment]
bro its literally Gmail, how tf can github mess up so bad

**Pull request merged**
